### PR TITLE
Add shapes through buttons

### PR DESCRIPTION
**Pull request by albfan**
To try this you need svgdep avaliable, which needs:

gsvgtk
gsvg
gresg
gxml

All repos are plain to build and install

Then you can add svg at wish

I try with complex svg and they fail miserably, not sure were fix is needed, probably gsvg

Example:

http://kyletezak.com/img/four-icon-challenge/four-icon-challenge-01.svg
http://kyletezak.com/img/four-icon-challenge/four-icon-challenge-02.svg

### CODE REVIEW

**Comment by albfan** [comment]
gsvgtk was updated, so I did on this PR, just to compile. But now svg load is broken

**Comment by Philip-Scott** [comment]
Mmm did you install all the dependencies from master? Getting this error while compiling atm :/ 

```
../src/Widgets/Shapes/GSVGtkShapeImage.vala:29.38-29.61: error: The type name `GSvgtk.ActorImageClutter' could not be found
public class Gcav.GSvgtkShapeImage : GSvgtk.ActorImageClutter, Gcav.Item {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 13 warning(s)
```

**Comment by albfan** [comment]
There's an update on gsvgtk. You need to compile from master

**Comment by albfan** [comment]
branch moved to upstream. Not all is buildable with flatpak

**Pull request closed without merging**
