### PR TITLE
Add new Item interface

### PR DESCRIPTION
**Pull request by esodan**
For Issue #19 this the idea on converting to interfaces.

### CODE REVIEW

**Comment by esodan** [comment]
Take a look at commit 074d7cd, I've added a shape to add SVG images from strings.
A default SVG image is loaded if no one has been set.

**Comment by Philip-Scott** [comment]
Can you add gsvgtk, and all it's deps to the Readme? :)

**Comment by esodan** [comment]
I had to change namespace in GSVGtk, so update is in place.

Dependencies are in place too.

**Comment by esodan** [comment]
@Alecaddd may you want to design a beauty No Image SVG.

**Comment by Alecaddd** [comment]
@esodan wouldn't be better to generate a grey filled box when creating an actor the first time?

**Comment by Philip-Scott** [comment]
@Alecaddd The defaults could be later set per-app by just replacing the original SVG :)

**Comment by esodan** [comment]
This should be enough for this PR.
Next large change maybe could be on mouse over and resizer, as they are classes not interfaces, but may no a big one.
Here at GSVGtk, will care to keep things "just work" for Gcav as new actors or features are added

**Review by Philip-Scott — APPROVED** [review]
I was finally able to compile it on my machine! I'm guessing that me installing one of the libraries in the wrong place made it be linked from a different location.

**Pull request merged**
